AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'app/controllers/users/*'

Documentation:
  Enabled: false
  
Metrics/LineLength:
  Max: 130

Style/ClassAndModuleChildren:
  Enabled: false
